version: '3.8'

services:
  web:
    image: ghcr.io/juniorbra/prefilheus:latest@sha256:81b9cfc8b826bd6198400996602660215d2fd765c46c
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.prefilheus.rule=Host(`ilheus.zobot.top`)
        - traefik.http.routers.prefilheus.entrypoints=websecure
        - traefik.http.routers.prefilheus.tls.certresolver=letsencryptresolver
        - traefik.http.services.prefilheus.loadbalancer.server.port=80
        - traefik.http.services.prefilheus.loadbalancer.passHostHeader=true
        - traefik.http.routers.prefilheus.service=prefilheus

networks:
  portainer:
    external: true
    name: portainer
